name: Selenium BDD CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:
  schedule:
    - cron: '30 6 * * 6,0'

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Verify Chrome Version
      run: chrome --version

    - name: Run Selenium BDD Tests with Maven
      run: mvn -B clean test -Dcucumber.options="--plugin html:target/cucumber-reports/report.html"

    - name: Upload Cucumber Report
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: Cucumber-Extent-Report
        path: target/cucumber-reports

    - name: Send Teams Message
      if: success() || failure()
      uses: Test_Shop/teams-notify-build-status@v3
      with: 
        webhookUrl: ${{ secrets.TEAMS_WEBHOOK_URL }}
        title: ISE UI Automation
        message: Ran the E2E UI automated tests
        titleBackgroundColor: ${{ job.status }}
        status: ${{ job.status }}
      env:
        SHOULD_DISPLAY_ACTOR_LABEL: true
        SHOULD_DISPLAY_VIEW_RUN_BUTTON: true
        SHOULD_DISPLAY_VIEW_COMMIT_BUTTON: false
